apiVersion: apps/v1
kind: Deployment
metadata:
  name: rangeplusclient-api-deployment
spec:
  selector:
    matchLabels:
      app: rangeplusclient-api
  template:
    metadata:
      labels:
        app: rangeplusclient-api
    spec:
      containers:
      - name: rangeplusclient-api
        image: mikebirkett/rangeplusclient-api
        ports:
          - containerPort: 9000